name: traefik

services:
  traefik:
    image: dhi.io/traefik:3
    container_name: traefik
    user: ":${DOCKER_ID}"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8081:8081" # Pi-hole dashboard
      - "2283:2283"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic_conf.yml:/etc/traefik/dynamic_conf.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs:/certs
    env_file:
      - .env
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      
networks:
  proxy:
    external: true
    name: homeserver_proxy
