name: traefik

services:
  traefik:
    image: dhi.io/traefik:3
    container_name: traefik
    ports:
      - "80:8000"
      - "443:8443"
      - "8080:8080"
      - "2283:2283"
      - "3000:3000"
      - "9090:9090"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    group_add:
      - ${DOCKER_ID}
    networks:
      - proxy
      
networks:
  proxy:
    external: true
    name: homeserver_proxy
