global:
  sendAnonymousUsage: false

log:
  level: INFO

api:
  dashboard: true
  insecure: true # FIXME: false

entryPoints:
  web:
    address: ":8000"
  websecure:
    address: ":8443"
  web-immich:
    address: ":2283"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: homeserver_proxy

# Enable insecure backends (e.g. Portainer HTTPS)
serversTransport:
  insecureSkipVerify: true
