name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    healthcheck:
      disable: false
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    labels:
      - "traefik.http.routers.whoami.rule=Host(`${LOCAL_IP}`)"

  redis:
    container_name: immich_redis
    image: dhi.io/redis:8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy

  database:
    container_name: immich_postgres
    image: dhi.io/postgres:18-alpine3.22
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    shm_size: 128mb
    healthcheck:
      disable: false
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: homeserver_proxy
